# Netlify Configuration File for Clean URLs

# This is the ONLY rule you need.
# It acts as a "smart" fallback for any request that doesn't match an existing file.
#
# How it works:
# 1. Request for /contact comes in.
# 2. Netlify looks for /contact.html (due to Pretty URLs) in the root. It's not there.
# 3. Netlify would normally serve a 404 error.
# 4. This rule intercepts the 404 and says "Wait! Try serving /pages/contact.html instead."
# 5. The file is found and served with a 200 OK status, and the URL remains /contact.
#
# This also works for the homepage (/) because /index.html exists and is found immediately,
# so the 404 rule is never triggered for it. The same applies to your /assets files.

[[rewrites]]
  from = "/*"
  to = "/pages/:splat.html"
  status = 404